import Head from "next/head";
import Search from "../components/Search/Search";

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJS Countries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Search />
    </>
  );
}
