import Head from "next/head";
import CardHeader from "../components/CardHeader/CardHeader";
import GroupCard from "../components/Card/GroupCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJS Countries</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CardHeader />

      <GroupCard />
    </>
  );
}
